mkdir: missing operand
Try 'mkdir --help' for more information.
mkdir: missing operand
Try 'mkdir --help' for more information.
mkdir: missing operand
Try 'mkdir --help' for more information.
/nvme/h/buildsets/eb_nepheli/software/SciPy-bundle/2021.10-foss-2021b/lib/python3.9/site-packages/scipy/optimize/optimize.py:282: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "
/onyx/data/simea/nikolas/postDoc/Active-Learning-Package/main_scripts/FF_Develop.py:2653: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
  plt.show()
mkdir: missing operand
Try 'mkdir --help' for more information.
mkdir: missing operand
Try 'mkdir --help' for more information.
mkdir: missing operand
Try 'mkdir --help' for more information.
mkdir: missing operand
Try 'mkdir --help' for more information.
Traceback (most recent call last):
  File "/nvme/h/buildsets/eb_nepheli/software/SciPy-bundle/2021.10-foss-2021b/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Energy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/onyx/data/simea/nikolas/postDoc/Active-Learning-Package/test_actlearnNO2/../main_scripts/evaluate_predictions.py", line 61, in <module>
    main()
  File "/onyx/data/simea/nikolas/postDoc/Active-Learning-Package/test_actlearnNO2/../main_scripts/evaluate_predictions.py", line 48, in main
    al.make_absolute_Energy_to_interaction(data,setup)
  File "/onyx/data/simea/nikolas/postDoc/Active-Learning-Package/main_scripts/FF_Develop.py", line 1049, in make_absolute_Energy_to_interaction
    data['Absolute Energy'] = data['Energy'].copy()
  File "/nvme/h/buildsets/eb_nepheli/software/SciPy-bundle/2021.10-foss-2021b/lib/python3.9/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/nvme/h/buildsets/eb_nepheli/software/SciPy-bundle/2021.10-foss-2021b/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Energy'
